baseURL: 'http://xupisco.net'
author: Leandro Voltolino
title: '@xupisco - Let''s build stuff'
theme: cocoa
publishDir: ../blog_public
disqusshortname: xupisco
googleAnalytics: UA-8395201-1
pygmentsuseclasses: false
permalinks:
  fixed: ':title/'
  post: 'post/:slug/'

menu:
  main:
    - name: Blog
      weight: -110
      identifier: blog
      url: /
    - name: FlappyBird Tutorial
      weight: -100
      identifier: flappybird-tutorial
      url: /flappybird-tutorial/

params:
  latestpostscount: 7
  i18n_flags: false
  author: xupisco
  avatar: img/zen.png
  cachebuster: true
  dateform: 02/01/2006
  dateformfull: 'Mon Jan 2 2006 15:04:05 MST'
  description: 'Calma, estou aqui para ajudar!'
  email: dev@xupisco.net
  highlightjs: true
  highlightjsStyle: atom-one-dark
  faviconfile: img/zen.png
  extracssfiles:
    - /css/customize.css
  lang: pt-br
  noshowreadtime: false
  twitter: //twitter.com/xupisco
  github: //github.com/xupisco
  selfintro: // insert clever quote here
  defaultContentLanguage: br
  enableRobotsTXT: true
  social:
    github: xupisco
    facebook: xupisco
    facebook_admin: '830831574'
    twitter: xupisco
    twitter_domain: xupisco.net
  authors:
    leandro:
      name: Leandro Voltolino
      thumbnail: 'http://pub.xupisco.net/avatar_small.png'
      images:
        - 'https://xupisco.net/img/zen.png'
      bio: I like turtles...
      email: xupisco@gmail.com
      social:
        github: xupisco
        facebook: xupisco
        twitter: xupisco
