baseURL: '/'
author: Leandro Voltolino
title: '@nerdicas - Let''s build stuff'
theme: cocoa
publishDir: public

disqusshortname: nerdicas
googleAnalytics: UA-8395201-1
pygmentsuseclasses: false
permalinks:
  fixed: ':title/'
  post: 'post/:slug/'

menu:
  main:
    - name: Blog
      weight: -110
      identifier: blog
      url: /
    - name: FlappyBird Tutorial
      weight: -100
      identifier: flappybird-tutorial
      url: /flappybird-tutorial/

related:
  threshold: 80
  includeNewer: false
  toLower: false
  indices:
  - name: tags
    weight: 100
  - name: keywords
    weight: 80
  - name: date
    weight: 10

params:
  latestpostscount: 0
  i18n_flags: false
  author: nerdicas
  avatar: /img/zen.png
  cachebuster: true
  dateform: 02/01/2006
  dateformfull: 'Mon Jan 2 2006 15:04:05 MST'
  description: 'Calma, estou aqui para ajudar!'
  email: dev@nerdicas.com
  highlightjs: true
  highlightjsStyle: atom-one-dark
  faviconfile: /img/zen.png
  
  extracssfiles:
    - /css/customize.css
    
  lang: pt-br
  noshowreadtime: false
  twitter: //twitter.com/nerdicas
  github: //github.com/xupisco
  selfintro: // insert clever quote here
  defaultContentLanguage: br
  enableRobotsTXT: true
  
  social:
    github: xupisco
    facebook: nerdicas
    facebook_admin: '830831574'
    twitter: nerdicas
    twitter_domain: nerdicas.com
    
  authors:
    leandro:
      name: Leandro Voltolino
      thumbnail: 'https://nerdicas.com/avatar_small.png'
      images:
        - 'https://nerdicas.com/img/zen.png'
      bio: I like turtles...
      email: blog@nerdicas.com
      social:
        github: xupisco
        facebook: nerdicas
        twitter: nerdicas
